### ISSUE TITLE
Polyfill doesn't work in Angular 

### ISSUE THREAD

**Issue by hamish-riahi** [pqina/filepond-polyfill#1]
Hi there,

I'm trying to use this polyfill in my angular with no luck.

Question?
Where should I reference the polyfill file? (Polyfill.ts, index.html, at module level)

**Comment by rikschennink** [comment]
I would advise to add the polyfills as a script to the index.html file. Or somehow prepend them to the output js file ( The `angular.json` file contains a `"scripts"` configuration section ).

**Comment by hamish-riahi** [comment]
Thanks for you answer. 

I have tried in index.html and angular-cli.json (Angular 5) and didn't work.
How I'm supposed to this this polyfill in Angular in general. (There is zero document for this)

I'm suspicious it has conflict with default polyfill.ts file!

**Comment by rikschennink** [comment]
Do you get any errors? If you look at the generated HTML file, is the polyfill loaded before the rest of the app logic? It should not conflict as it tests for native functionality, so as long as everything is already polyfilled it's not going to do anything.

**Comment by hamish-riahi** [comment]
I upgraded my project to Angular 6 the problem is still there.

Actually the whole app chunk doesn't load.
Here are the options I've tried so far:

1- Referenced the polyfill file into polyfill.ts(My preference)
2- Add the polyfill file path to scripts section in angular.json 
3- Directly added to index.html (Header / End of Body)

**Comment by rikschennink** [comment]
Do you get any errors? The polyfill is there to make it work on older browsers. So I expect it throws some sort of missing functionality error.

**Comment by hamish-riahi** [comment]
The whole app chunk doesn't load.. IE11 cannot load the main application chunk js file so i don't get any detail error unfortunately.

Thanks for your quick response.

**Comment by rikschennink** [comment]
But I would suspect IE11 throwing an error in its developer console, right?

**Comment by hamish-riahi** [comment]
Yes. The whole angular project doesn't load (Blank page) and when I check the developer console it says : 
```
Uncaught (in promise): Error: Loading chunk 3 failed. 
(missing: https://****/3.*****.js)
at Anonymous function (https://*******/main.*****.js:*****) 
```

**Comment by rikschennink** [comment]
Is this the error you get when you add it directly in the HTML file, as a separate JS script, before the Angular application is loaded?

**Comment by hamish-riahi** [comment]
Yes. No matter how I add the file I get this error.

**Comment by rikschennink** [comment]
Okay, I will try to test this later this week.

**Comment by rikschennink** [comment]
Just tested with this HTML.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ngx</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <script src="assets/filepond-polyfill.js"></script>

</head>
<body>
  <app-root></app-root>
</body>
</html>
```

Whether I load the filepond polyfill file or not, IE11 errors out on the angular polyfill.js file.

See error below:

![screen shot 2018-06-14 at 09 08 49](https://user-images.githubusercontent.com/1132575/41396959-de9a0336-6fb2-11e8-8b6c-fa26aafd4cdc.png)

**Comment by hamish-riahi** [comment]
You need to install and include some of the polyfill packages commented in the polyfill.ts file in your project (the file generated by angular cli ) then it will work .

**Comment by rikschennink** [comment]
Ah thanks! 

Uncommented these lines:

```js
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
//import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
```

It now functions as intended:

![screen shot 2018-06-14 at 09 56 22](https://user-images.githubusercontent.com/1132575/41398962-551a2ec2-6fb9-11e8-825e-586ab2c2481d.png)

**Comment by hamid-riahi** [comment]
Interesting. Thanks!

I tried filepond without plugins in my main project and it works!

Still doesn't work with any plugin. (I'm using all plugins and tested them one by one)

My Module code:

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { FileUploadComponent } from "./file-upload.component";

import { FilePondModule, registerPlugin } from 'ngx-filepond';

import FilepondPluginFileEncode from 'filepond-plugin-file-encode/dist/filepond-plugin-file-encode.esm';
import FilepondPluginImagePreview  from 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm';
import FilepondPluginFileValidateType from 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm';
import FilepondPluginFileValidateSize from 'filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.esm';
import FilepondPluginImageExifOrientation from 'filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.esm';
import FilepondPluginImageCrop from 'filepond-plugin-image-crop/dist/filepond-plugin-image-crop.esm';
import FilepondPluginImageResize from 'filepond-plugin-image-resize/dist/filepond-plugin-image-resize.esm';
import FilepondPluginImageTransform from 'filepond-plugin-image-transform/dist/filepond-plugin-image-transform.esm';

registerPlugin(
  FilepondPluginFileEncode,
  FilepondPluginFileValidateType,
  FilepondPluginFileValidateSize,
  FilepondPluginImageExifOrientation,
  FilepondPluginImagePreview,
  FilepondPluginImageCrop,
  FilepondPluginImageResize,
  FilepondPluginImageTransform
);

@NgModule({
  declarations: [
    FileUploadComponent,
  ],
  imports: [
    CommonModule,
    FormsModule,   
    ReactiveFormsModule, 
    FilePondModule  
  ],
  exports: [FileUploadComponent],
  providers: []
})
export class FileUploadModule {
    constructor() {}
}

**Comment by hamish-riahi** [comment]
Interesting. Thanks!

I tried filepond without plugins in my main project and it works!

Still doesn't work with any plugin. (I'm using all plugins and tested them one by one)

My Module code:

```js
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { FileUploadComponent } from "./file-upload.component";

import { FilePondModule, registerPlugin } from 'ngx-filepond';

import FilepondPluginFileEncode from 'filepond-plugin-file-encode/dist/filepond-plugin-file-encode.esm';
import FilepondPluginImagePreview  from 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm';
import FilepondPluginFileValidateType from 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm';
import FilepondPluginFileValidateSize from 'filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.esm';
import FilepondPluginImageExifOrientation from 'filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.esm';
import FilepondPluginImageCrop from 'filepond-plugin-image-crop/dist/filepond-plugin-image-crop.esm';
import FilepondPluginImageResize from 'filepond-plugin-image-resize/dist/filepond-plugin-image-resize.esm';
import FilepondPluginImageTransform from 'filepond-plugin-image-transform/dist/filepond-plugin-image-transform.esm';

registerPlugin(
  FilepondPluginFileEncode,
  FilepondPluginFileValidateType,
  FilepondPluginFileValidateSize,
  FilepondPluginImageExifOrientation,
  FilepondPluginImagePreview,
  FilepondPluginImageCrop,
  FilepondPluginImageResize,
  FilepondPluginImageTransform
);

@NgModule({
  declarations: [
    FileUploadComponent,
  ],
  imports: [
    CommonModule,
    FormsModule,   
    ReactiveFormsModule, 
    FilePondModule  
  ],
  exports: [FileUploadComponent],
  providers: []
})
export class FileUploadModule {
    constructor() {}
}
```

**Comment by rikschennink** [comment]
This is my module setup, maybe removing the `.esm` from your imports will fix this?

```js
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

import { FilePondModule, registerPlugin } from 'ngx-filepond';

import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';

registerPlugin(FilePondPluginFileValidateType);

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FilePondModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by hamish-riahi** [comment]
Fantastic. worked.

I changed the path from:
```js
import FilepondPluginFileEncode from 'filepond-plugin-file-encode/dist/filepond-plugin-file-encode.esm';
```

to:
```js
import FilePondPluginFileEncode from 'filepond-plugin-file-encode';
```

Thanks.

**Comment by rikschennink** [comment]
No problem, glad to hear it's working!
