### ISSUE TITLE
[NUXT] [IE11] Filepond doesn't work

### ISSUE THREAD

**Issue by Askerx9** [pqina/filepond-polyfill#2]
Hi,

I try to import the polyfill in my project nuxt but nothing works I always have the same result on ie11:
**[nuxt] Error while mounting app: This object does not support this action**

![Capture](https://user-images.githubusercontent.com/15520511/54293968-28599c00-45b1-11e9-8ec5-40db4bd8bf4d.JPG)

when i disable filepond my app works fine!
How should I do, there is no doc!

Thanks for help :)

**Comment by rikschennink** [comment]
Does the polyfill load before FilePond?
