### ISSUE TITLE
Server side rendering failing

### ISSUE THREAD

**Issue by SilentImp** [pqina/filepond-polyfill#3]
Server side rendering is failing
if `window` is undefined `typeof window.CustomEvent` will rise en error.
We should check `typeof window` first.

**Comment by rikschennink** [comment]
Feel free to submit a PR

**Comment by SilentImp** [comment]
aha, later today

**Comment by SilentImp** [comment]
@rikschennink https://github.com/pqina/filepond-polyfill/pull/4
