### ISSUE TITLE
How to use filepond-polyfill with create react app

### ISSUE THREAD

**Issue by TRomesh** [pqina/filepond-polyfill#5]
I'm have added the filepond with the react plugin and it works well chrome but i need to get it working on the IE10 and IE11. I couldn't find proper documentation on how to use this. So how can i add it to create-react-app?

**Comment by rikschennink** [comment]
@TRomesh There is no support for IE10, you need both the filepond-polyfill and a promise polyfill to make it work on IE11. See the file below for example set up:
https://github.com/pqina/filepond-boilerplate-php/blob/master/public/index.html

**Comment by AliYmn** [comment]
@rikschennink 
is that true? i called before all of them.
``` javascript
import "filepond-polyfill"
```

**Comment by rikschennink** [comment]
> @rikschennink
> is that true? i called before all of them.
> 
> ```js
> import "filepond-polyfill"
> ```

You also need to add a promise polyfill.

Closed because inactive.
